parole = read.csv("parole.csv")
str(parole)
table(parole$violator)
str(parole)
parole$state = as.factor(parole$state)
parole$multiple.offenses = as.factor(parole$multiple.offenses)
parole$crime = as.factor(parole$crime)
summary(parole$state)
set.seed(144)
library(caTools)
split = sample.split(parole$violator, SplitRatio = 0.7)
train = subset(parole, split == TRUE)
test = subset(parole, split == FALSE)
model1 = glm(violator ~., data = train, family=binomial)
summary(model1)
predictTest = predict(model1, type="response", newdata = test)
summary(predictTest)
table(test$violator, as.numeric(predictTest >= 0.5))
12/(12+11)
167/(167+12)
(167+12)/(167+24+11)
library(ROCR)
pred = prediction(predictTest, test$violator)
as.numeric(performance(pred, "auc")@y.values)