songs = read.csv("songs.csv")
nrow(subset(songs,songs$artistname=="Michael Jackson"))
nrow(subset(songs, songs$year==2010))
MichaelJackson = subset(songs, songs$artistname=="Michael Jackson")
MichaelJackson$songtitle[MichaelJackson$Top10 == "1"]
str(songs)
table(songs$timesignature)
songs$songtitle[songs$tempo==max(songs$tempo)]
SongsTrain = subset(songs, songs$year<=2009)
SongsTest = subset(songs, songs$year==2010)
str(SongsTrain)
nonvars = c("year","songtitle","artistname","songID","artistID")
SongsTrain = SongsTrain[,!(names(SongsTrain)%in%nonvars)]
SongsTest = SongsTest[,!(names(SongsTest)%in%nonvars)]
SongsLog1 = glm(Top10 ~., data = SongsTrain, family=binomial)
summary(SongsLog1)
cor(SongsTrain$loudness, SongsTrain$energy)
SongsLog2 = glm(Top10 ~ . -loudness, data = SongsTrain, family=binomial)
summary(SongsLog2)
SongsLog3 = glm(Top10 ~ . -energy, data = SongsTrain, family=binomial)
summary(SongsLog3)
Predicttest = predict(SongsLog3, newdata = SongsTest, type="response")
table(SongsTest$Top10, Predicttest >= 0.45)
(309+19)/(309+5+40+19)
19/(40+19)
309/(309+5)