emails = read.csv("emails.csv", stringsAsFactors = FALSE)
str(emails)
table(emails$spam)
emails$text[1]
emails$text[50]
max(nchar(emails$text))
which.min(nchar(emails$text))
library(tm)
corpus = Corpus(VectorSource(emails$text))
corpus = tm_map(corpus, tolower)
corpus = tm_map(corpus, removePunctuation)
corpus = tm_map(corpus, removeWords, stopwords("english"))
corpus = tm_map(corpus, stemDocument)
dtm = DocumentTermMatrix(corpus)
dtm
spdtm = removeSparseTerms(dtm, 0.95)
spdtm
emailsSparse = as.data.frame(as.matrix(spdtm))
colnames(emailsSparse) = make.names(colnames(emailsSparse))
which.max(colSums(emailsSparse))
emailsSparse$spam = emails$spam
sort(colSums(subset(emailsSparse, spam == 0)))
sort(colSums(subset(emailsSparse, spam == 1)))
emailsSparse$spam = as.factor(emailsSparse$spam)
set.seed(123)
library(caTools)
spl = sample.split(emailsSparse, SplitRatio = 0.7)
train = subset(emailsSparse, spl == TRUE)
test = subset(emailsSparse, spl == FALSE)
spamLog = glm(spam ~ ., data = train, family = "binomial")
library(rpart)
spamCART = rpart(spam ~ ., data = train, method = "class")
library(randomForest)
spamRF = randomForest(spam ~ ., data = train)
predTrainlog = predict(spamLog, type = "response")
predTrainCART = predict(spamCART)[,2]
predTrainRF = predict(spamRF, type = "prob")[,2]
table(predTrainlog < 0.00001)
table(predTrainlog > 0.99999)
table(predTrainlog >= 0.00001 & predTrainlog <= 0.99999)
summary(spamLog)
library(rpart.plot)
prp(spamCART)
table(train$spam, predTrainlog>0.5)
(2978+917)/nrow(train)
library(ROCR)
predictionTrainLog = prediction(predTrainlog, train$spam)
as.numeric(performance(predictionTrainLog, "auc")@y.values)
table(train$spam, predTrainCART > 0.5)
(2900+894)/nrow(train)
predictionTrainCART = prediction(predTrainCART, train$spam)
as.numeric(performance(predictionTrainCART, "auc")@y.values)
table(train$spam, predTrainRF > 0.5)
(3002+916)/nrow(train)
predictionTrainRF = prediction(predTrainRF, train$spam)
as.numeric(performance(predictionTrainRF, "auc")@y.values)
predTestlog = predict(spamLog, newdata = test, type = "response")
predTestCART = predict(spamCART, newdata = test)[,2]
predTestRF = predict(spamRF, newdata = test, type = "prob")[,2]
table(test$spam, predTestlog > 0.5)
(1245+376)/nrow(test)
predictionTestlog = prediction(predTestlog, test$spam)
as.numeric(performance(predictionTestlog, "auc")@y.values)
table(test$spam, predTestCART > 0.5)
(1243+383)/nrow(test)
predictionTestCART = prediction(predTestCART, test$spam)
as.numeric(performance(predictionTestCART, "auc")@y.values)
table(test$spam, predTestRF > 0.5)
(1303+391)/nrow(test)
predictionTestRF = prediction(predTestRF, test$spam)
as.numeric(performance(predictionTestRF, "auc")@y.values)