trials = read.csv("clinical_trial.csv", stringsAsFactors = FALSE)
str(trials)
max(nchar(trials$abstract))
sum(nchar(trials$abstract) == 0)
which.min(nchar(trials$title))
trials$title[1258]
library(tm)
corpusTitle = Corpus(VectorSource(trials$title))
corpusAbstract = Corpus(VectorSource(trials$abstract))
corpusTitle = tm_map(corpusTitle, tolower)
corpusAbstract = tm_map(corpusAbstract, tolower)
corpusTitle = tm_map(corpusTitle, removePunctuation)
corpusAbstract = tm_map(corpusAbstract, removePunctuation)
corpusTitle = tm_map(corpusTitle, removeWords, stopwords("english"))
corpusAbstract = tm_map(corpusAbstract, removeWords, stopwords("english"))
corpusTitle = tm_map(corpusTitle, stemDocument)
corpusAbstract = tm_map(corpusAbstract, stemDocument)
dtmTitle = DocumentTermMatrix(corpusTitle)
dtmAbstract = DocumentTermMatrix(corpusAbstract)
dtmTitle = removeSparseTerms(dtmTitle, 0.95)
dtmAbstract = removeSparseTerms(dtmAbstract, 0.95)
dtmTitle = as.data.frame(as.matrix(dtmTitle))
dtmAbstract = as.data.frame(as.matrix(dtmAbstract))
str(dtmTitle)
str(dtmAbstract)
which.max(colSums(dtmAbstract))
colnames(dtmTitle) = paste0("T", colnames(dtmTitle))
colnames(dtmAbstract) = paste0("A", colnames(dtmAbstract))
dtm = cbind(dtmTitle, dtmAbstract)
dtm$trial = trials$trial
str(dtm)
set.seed(144)
library(caTools)
spl = sample.split(dtm$trial, 0.7)
train = subset(dtm, spl == TRUE)
test = subset(dtm, spl == FALSE)
table(train$trial)
730/(730+572)
library(rpart)
trialCART = rpart(trial ~., data = train, method = "class")
library(rpart.plot)
prp(trialCART)
predTrain = predict(trialCART)[,2]
summary(predTrain)
table(train$trial, predTrain>=0.5)
(631+441)/nrow(train)
441/(441+131)
631/(631+99)
predTest = predict(trialCART, newdata = test, type = "class")
table(test$trial, predTest)
(261+162)/nrow(test)
library(ROCR)
predTest = predict(trialCART, newdata = test)[,2]
pred = prediction(predTest, test$trial)
as.numeric(performance(pred, "auc")@y.values)