wiki = read.csv("wiki.csv", stringsAsFactors = FALSE)
wiki$Vandal = as.factor(wiki$Vandal)
table(wiki$Vandal)
library(tm)
corpusAdded = Corpus(VectorSource(wiki$Added))
corpusAdded = tm_map(corpusAdded, removeWords, stopwords("english"))
corpusAdded = tm_map(corpusAdded, stemDocument)
dtmAdded = DocumentTermMatrix(corpusAdded)
dtmAdded
sparseAdded = removeSparseTerms(dtmAdded, 0.997)
sparseAdded
wordsAdded = as.data.frame(as.matrix(sparseAdded))
colnames(wordsAdded) = paste("A", colnames(wordsAdded))
corpusRemoved = Corpus(VectorSource(wiki$Removed))
corpusRemoved = tm_map(corpusRemoved, removeWords, stopwords("english"))
corpusRemoved = tm_map(corpusRemoved, stemDocument)
dtmReversed = DocumentTermMatrix(corpusRemoved)
sparseRemoved = removeSparseTerms(dtmReversed, 0.997)
wordsRemoved = as.data.frame(as.matrix(sparseRemoved))
colnames(wordsRemoved) = paste("R", colnames(wordsRemoved))
ncol(wordsRemoved)
wikiWords = cbind(wordsAdded, wordsRemoved)
wikiWords$Vandal = wiki$Vandal
library(caTools)
set.seed(123)
spl = sample.split(wikiWords$Vandal, SplitRatio = 0.7)
wikiTrain = subset(wikiWords, spl == TRUE)
wikiTest = subset(wikiWords, spl == FALSE)
table(wikiTest$Vandal)
618/(618+545)
library(rpart)
CARTmodel1 = rpart(Vandal ~ ., data = wikiTrain, method = "class")
predmodel1 = predict(CARTmodel1, newdata = wikiTest, type = "class")
table(wikiTest$Vandal, predmodel1)
(614+19)/nrow(wikiTest)
library(rpart.plot)
prp(CARTmodel1)
wikiWords2 = wikiWords
wikiWords2$HTTP = ifelse(grepl("http",wiki$Added, fixed = TRUE),1,0)
table(wikiWords2$HTTP)
wikiTrain2 = subset(wikiWords2, spl == TRUE)
wikiTest2 = subset(wikiWords2, spl == FALSE)
CARTmodel2 = rpart(Vandal ~ ., data = wikiTrain2, method = "class")
predmodel2 = predict(CARTmodel2, newdata = wikiTest2, type = "class")
table(wikiTest2$Vandal, predmodel2)
(605+13)/(nrow(wikiTest2))
wikiWords2$NumWordsAdded = rowSums(as.matrix(dtmAdded))
wikiWords2$NumWordsRemoved = rowSums(as.matrix(dtmReversed))
mean(wikiWords2$NumWordsAdded)
wikiTrain3 = subset(wikiTrain2, spl == TRUE)
wikiTest3 = subset(wikiTest2, spl == FALSE)
CARTmodel3 = rpart(Vandal ~ ., data = wikiTrain3, method = "class")
predmodel3 = predict(CARTmodel3, newdata = wikiTest3, type = "class")
table(wikiTest3$Vandal, predmodel3)
(181+15)/nrow(wikiTest3)
wikiWords3 = wikiWords2
wikiWords3$Minor = wiki$Minor
wikiWords3$Loggedin = wiki$Loggedin
wikiTrain4 = subset(wikiWords3, spl == TRUE)
wikiTest4 = subset(wikiWords3, spl == FALSE)
CARTmodel4 = rpart(Vandal ~ ., data = wikiTrain4, method = "class")
predmodel4 = predict(CARTmodel4, newdata = wikiTest4, type = "class")
table(wikiTest4$Vandal, predmodel4)
(595+241)/nrow(wikiTest4)
prp(CARTmodel4)