dailykos = read.csv("dailykos.csv")
kodDist = dist(dailykos, method = "euclidean")
kodCluster = hclust(kodDist, method = "ward.D")
plot(kodCluster)
clusterGroups = cutree(kodCluster, k = 7)
cluster1 = subset(dailykos, clusterGroups == 1)
cluster2 = subset(dailykos, clusterGroups == 2)
cluster3 = subset(dailykos, clusterGroups == 3)
cluster4 = subset(dailykos, clusterGroups == 4)
cluster5 = subset(dailykos, clusterGroups == 5)
cluster6 = subset(dailykos, clusterGroups == 6)
cluster7 = subset(dailykos, clusterGroups == 7)
nrow(cluster3)
nrow(cluster1)
nrow(cluster2)
nrow(cluster4)
nrow(cluster5)
nrow(cluster6)
nrow(cluster7)
tail(sort(colMeans(cluster1)))
tail(sort(colMeans(cluster2)))
tail(sort(colMeans(cluster5)))
set.seed(1000)
kmeanscluster = kmeans(dailykos, centers = 7)
table(kmeanscluster$cluster)
kMeansCluster = split(dailykos, kmeanscluster$cluster)
tail(sort(colMeans(kMeansCluster[[1]])))
tail(sort(colMeans(kMeansCluster[[2]])))
tail(sort(colMeans(kMeansCluster[[3]])))
tail(sort(colMeans(kMeansCluster[[4]])))
tail(sort(colMeans(kMeansCluster[[5]])))
tail(sort(colMeans(kMeansCluster[[6]])))
tail(sort(colMeans(kMeansCluster[[7]])))
table(clusterGroups, kmeanscluster$cluster)