stocks = read.csv("StocksCluster.csv")
nrow(stocks)
str(stocks)
table(stocks$PositiveDec)
6324/(6324+5256)
cor(stocks)
summary(stocks)
set.seed(144)
library(caTools)
spl = sample.split(stocks$PositiveDec, SplitRatio = 0.7)
train = subset(stocks, spl == TRUE)
test = subset(stocks, spl == FALSE)
StocksModel = glm(PositiveDec ~ ., data = train, family = "binomial")
predModel = predict(StocksModel, type = "response")
table(train$PositiveDec, predModel>0.5)
(990+3640)/nrow(train)
predTestModel = predict(StocksModel, newdata = test, type = "response")
table(test$PositiveDec, predTestModel>0.5)
(417+1553)/nrow(test)
table(test$PositiveDec)
1897/(1577+1897)
limitedTrain = train
limitedTrain$PositiveDec = NULL
limitedTest = test
limitedTest$PositiveDec = NULL
library(caret)
preproc = preProcess(limitedTrain)
normTrain = predict(preproc, limitedTrain)
normTest = predict(preproc, limitedTest)
mean(normTrain$ReturnJan)
mean(normTest$ReturnJan)
set.seed(144)
km = kmeans(normTrain, centers = 3)
table(km$cluster)
library(flexclust)
km.kcca = as.kcca(km, normTrain)
clusterTrain = predict(km.kcca)
clusterTest = predict(km.kcca, newdata = normTest)
table(clusterTest)
stocksTrain1 = subset(train, clusterTrain == 1)
stocksTrain2 = subset(train, clusterTrain == 2)
stocksTrain3 = subset(train, clusterTrain == 3)
stocksTest1 = subset(test, clusterTest == 1)
stocksTest2 = subset(test, clusterTest == 2)
stocksTest3 = subset(test, clusterTest == 3)
mean(stocksTrain1$PositiveDec)
mean(stocksTrain2$PositiveDec)
mean(stocksTrain3$PositiveDec)
StocksModel1 = glm(PositiveDec ~ ., data = stocksTrain1, family = binomial)
StocksModel2 = glm(PositiveDec ~ ., data = stocksTrain2, family = binomial)
StocksModel3 = glm(PositiveDec ~ ., data = stocksTrain3, family = binomial)
summary(StocksModel1)
summary(StocksModel2)
summary(StocksModel3)
PredictTest1 = predict(StocksModel1, newdata = stocksTest1, type = "response")
PredictTest2 = predict(StocksModel2, newdata = stocksTest2, type = "response")
PredictTest3 = predict(StocksModel3, newdata = stocksTest3, type = "response")
table(stocksTest1$PositiveDec, PredictTest1 > 0.5)
(30+774)/nrow(stocksTest1)
table(stocksTest2$PositiveDec, PredictTest2 > 0.5)
(388+757)/nrow(stocksTest2)
table(stocksTest3$PositiveDec, PredictTest3 > 0.5)
(49+13)/nrow(stocksTest3)
AllPredictions = c(PredictTest1, PredictTest2, PredictTest3)
AllOutcomes = c(stocksTest1$PositiveDec, stocksTest2$PositiveDec, stocksTest3$PositiveDec)
table(AllOutcomes, AllPredictions > 0.5)
(467+1544)/(467+1110+353+1544)