airlines = read.csv("AirlinesCluster.csv")
summary(airlines)
library(caret)
preproc = preProcess(airlines)
airlinesNorm = predict(preproc, airlines)
summary(airlinesNorm)
distances = dist(airlinesNorm, method = "euclidean")
cluster = hclust(distances, method = "ward.D")
plot(cluster)
clusterGroups = cutree(cluster, k = 5)
table(clusterGroups)
colMeans(subset(airlines, clusterGroups == 1))
colMeans(subset(airlines, clusterGroups == 2))
colMeans(subset(airlines, clusterGroups == 3))
colMeans(subset(airlines, clusterGroups == 4))
colMeans(subset(airlines, clusterGroups == 5))
set.seed(88)
kmeansClust = kmeans(airlinesNorm, centers = 5, iter.max = 1000)
table(kmeansClust$cluster)