gerber = read.csv("gerber.csv")
str(gerber)
table(gerber$voting)
108696/(108696+235388)
tapply(gerber$voting, gerber$civicduty, mean)
tapply(gerber$voting, gerber$hawthorne, mean)
tapply(gerber$voting, gerber$self, mean)
tapply(gerber$voting, gerber$neighbors, mean)
model1 = glm(voting ~ hawthorne + civicduty + neighbors + self, data = gerber, family = "binomial")
summary(model1)
predictLog = predict(model1, type="response")
table(gerber$voting, predictLog > 0.3)
(134513+51966)/(134516+100875+56730+51966)
table(gerber$voting, predictLog > 0.5)
(235388)/(235388+108696)
library(ROCR)
ROCRpred = prediction(predictLog, gerber$voting)
as.numeric(performance(ROCRpred, "auc")@y.values)
library(rpart)
CARTmodel = rpart(voting ~ civicduty + hawthorne + self + neighbors, data = gerber)
library(rpart.plot)
prp(CARTmodel)
CARTmodel2 = rpart(voting ~ civicduty + hawthorne + self + neighbors, data = gerber, cp = 0.0)
prp(CARTmodel2)
CARTmodel3 = rpart(voting ~ civicduty + hawthorne + self + neighbors + sex, data = gerber, cp = 0.0)
prp(CARTmodel3)
CARTmodel4 = rpart(voting ~ control, data = gerber, cp = 0.0)
prp(CARTmodel4, digits = 6)
CARTmodel5 = rpart(voting ~ control + sex, data = gerber, cp = 0.0)
prp(CARTmodel5, digits = 6)
abs(0.34-0.296638)
model2 = glm(voting ~ sex + control, data = gerber, family = "binomial")
summary(model2)
Possibilites = data.frame(sex=c(0,0,1,1),control=c(0,1,0,1))
predict(model2, newdata = Possibilites, type = "response")
abs(0.290456-0.2908065)
model2 = glm(voting ~ sex + control + sex:control, data = gerber, family = "binomial")
summary(model2)
predict(model2, newdata = Possibilites, type = "response")