letter = read.csv("letters_ABPR.csv")
letter$isB = as.factor(letter$letter == "B")
library(caTools)
set.seed(1000)
spl = sample.split(letter$isB, SplitRatio=0.5)
Train = subset(letter, spl == TRUE)
Test = subset(letter, spl == FALSE)
table(Test$isB)
1175/(1175+383)
library(rpart)
CARTmodel1 = rpart(isB ~ . -letter, data = Train, method = "class")
predictions = predict(CARTmodel1, newdata = Test, type = "class")
table(Test$isB, predictions)
(1134+327)/nrow(Test)
set.seed(1000)
library(randomForest)
RFmodel = randomForest(isB ~ . -letter, data = Train)
predictions = predict(RFmodel, newdata = Test)
table(Test$isB, predictions)
(1161+371)/(1161+14+12+371)
letter$letter = as.factor(letter$letter)
set.seed(2000)
spl = sample.split(letter$letter, SplitRatio = 0.5)
Train2 = subset(letter, spl == TRUE)
Test2 = subset(letter, spl == FALSE)
table(Train2$letter)
table(Test2$letter)
401/nrow(Test)
CARTmodel2 = rpart(letter ~ . -isB, data = Train2, method = "class")
predictLetter = predict(CARTmodel2, newdata = Test2, type = "class")
table(Test2$letter, predictLetter)
(348+318+363+340)/nrow(Test2)
set.seed(1000)
RFmodel2 = randomForest(letter ~ . -isB, data = Train2)
predictLetter = predict(RFmodel2, newdata = Test2)
table(Test2$letter, predictLetter)
(391+380+394+362)/nrow(Test2)